# Generated by Django 5.0 on 2025-12-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('SALIDA_AREA', 'Salida del Área Segura'), ('BATERIA_BAJA', 'Batería Baja'), ('SIN_SEÑAL', 'Sin Señal GPS'), ('MANUAL', 'Alerta Manual')], default='SALIDA_AREA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_enviada', models.DateTimeField(auto_now_add=True)),
                ('enviada_exitosamente', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('mensaje_id', models.CharField(blank=True, help_text='ID del mensaje en Firebase/servicio push', max_length=255)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si el envío falló')),
            ],
            options={
                'verbose_name': 'Notificación a Tutor',
                'verbose_name_plural': 'Notificaciones a Tutores',
                'ordering': ['-fecha_enviada'],
            },
        ),
    ]
