# Generated by Django 5.0 on 2025-12-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('core', '0001_initial'),
        ('gis_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gis_tracking.nino'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='posicion_gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='gis_tracking.posiciongps'),
        ),
        migrations.AddField(
            model_name='notificaciontutor',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alerta'),
        ),
        migrations.AddField(
            model_name='notificaciontutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tutores_notificados',
            field=models.ManyToManyField(related_name='alertas_recibidas', through='alerts.NotificacionTutor', to='core.tutor'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['nino', '-fecha_creacion'], name='alerts_aler_nino_id_523bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='alerts_aler_estado_7a8dab_idx'),
        ),
    ]
