# Generated by Django 5.0 on 2025-12-06 23:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(help_text='Código único del centro educativo', max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('area_segura', django.contrib.gis.db.models.fields.PolygonField(help_text='Polígono que delimita el área segura del kinder', srid=4326)),
                ('ubicacion_centro', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Punto central del kinder (calculado del polígono)', null=True, srid=4326)),
                ('margen_metros', models.IntegerField(default=0, help_text='Margen adicional en metros fuera del polígono (geofencing)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centro Educativo',
                'verbose_name_plural': 'Centros Educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ninos/fotos/')),
                ('dispositivo_id', models.CharField(blank=True, help_text='ID del celular/smartwatch para tracking', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('tracking_activo', models.BooleanField(default=True, help_text='Si el tracking GPS está activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('centro_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ninos', to='gis_tracking.centroeducativo')),
                ('tutor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ninos_principal', to='core.tutor')),
                ('tutores_adicionales', models.ManyToManyField(blank=True, help_text='Tutores adicionales que reciben alertas', related_name='ninos_adicional', to='core.tutor')),
            ],
            options={
                'verbose_name': 'Niño/a',
                'verbose_name_plural': 'Niños/as',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PosicionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas GPS (latitud, longitud)', srid=4326)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dentro_area_segura', models.BooleanField(default=True, help_text='¿El niño está dentro del área del kinder?')),
                ('precision_metros', models.FloatField(blank=True, help_text='Precisión del GPS en metros', null=True)),
                ('altitud', models.FloatField(blank=True, help_text='Altitud en metros', null=True)),
                ('velocidad_kmh', models.FloatField(blank=True, help_text='Velocidad en km/h', null=True)),
                ('nivel_bateria', models.IntegerField(blank=True, help_text='Nivel de batería del dispositivo (0-100)', null=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='gis_tracking.nino')),
            ],
            options={
                'verbose_name': 'Posición GPS',
                'verbose_name_plural': 'Posiciones GPS',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nino', '-timestamp'], name='gis_trackin_nino_id_960d43_idx'), models.Index(fields=['dentro_area_segura', '-timestamp'], name='gis_trackin_dentro__c82d17_idx')],
            },
        ),
    ]
